import type { RoomSlot } from '../../lib/room/roomProgress';

/**
 * The outline of the piece each slot is waiting for, in room space.
 *
 * A list of closed loops per slot — one for most pieces, two for a garland
 * strung across both walls.
 *
 * Generated by `scripts/build-ghost-contours.mjs` — see that file for why
 * these are traced rather than taken from the art directly. Do not hand-edit;
 * re-run the script when the room art changes.
 */
export type GhostPoint = readonly [x: number, y: number];

export const ROOM_GHOST_SHAPES: Record<RoomSlot, readonly (readonly GhostPoint[])[]> = {
  // authored shape — 1 loop
  day1: [
    [
      [0, 59.3],
      [88.4, 113],
      [0, 166.7],
      [-88.4, 113],
    ],
  ],
  // traced from dresser — 1 loop
  day2: [
    [
      [76, 0.6],
      [96.4, 12.6],
      [106, 12.6],
      [107.2, 5.4],
      [112, 4.2],
      [119.2, 24.6],
      [131.2, 31.8],
      [131.2, 83.4],
      [107.2, 97.8],
      [50.8, 66.6],
      [50.8, 15],
    ],
  ],
  // traced from wardrobe — 1 loop
  day3: [
    [
      [-47.2, -60.4],
      [-34, -53.2],
      [-34, 35.6],
      [-84.4, 63.2],
      [-96.4, 56],
      [-96.4, -31.6],
      [-71.2, -46],
      [-66.4, -55.6],
    ],
  ],
  // traced from fishbowl — 1 loop
  day4: [
    [
      [41.5, 94.9],
      [48.7, 94.9],
      [55.9, 100.9],
      [57.1, 116.5],
      [61.9, 120.1],
      [61.9, 135.7],
      [45.1, 145.3],
      [28.3, 135.7],
      [28.3, 120.1],
      [33.1, 116.5],
      [33.1, 103.3],
    ],
  ],
  // traced from mirror — 1 loop
  day5: [
    [
      [-78.3, -102.3],
      [-61.5, -99.9],
      [-56.7, -92.7],
      [-56.7, -78.3],
      [-67.5, -56.7],
      [-78.3, -47.1],
      [-89.1, -44.7],
      [-98.7, -51.9],
      [-98.7, -69.9],
      [-93.9, -81.9],
    ],
  ],
  // traced from porthole — 1 loop
  day6: [
    [
      [69.1, -103.5],
      [90.7, -93.9],
      [107.5, -71.1],
      [113.5, -42.3],
      [111.1, -32.7],
      [102.7, -25.5],
      [94.3, -24.3],
      [83.5, -27.9],
      [71.5, -37.5],
      [58.3, -57.9],
      [53.5, -72.3],
      [53.5, -89.1],
      [61.9, -102.3],
    ],
  ],
  // authored shape — 2 loops
  day7: [
    [
      [9, -160],
      [140, -80],
      [140, -56],
      [9, -136],
    ],
    [
      [-9, -160],
      [-140, -80],
      [-140, -56],
      [-9, -136],
    ],
  ],
};
