import type { ProgramPlanId } from '../../program/domain/programCatalogue';
import type { LessonId } from './lessonCatalogue';
import type { PressureLessonTrack } from './pressureLessonTrack';

/** Frozen teaching editions before every plan had a goal-specific opening. */
export const PRE_ALL_GOAL_FIRST_LESSON_SEQUENCES: Partial<Record<ProgramPlanId, readonly LessonId[]>> = {
  night: [
    'breath.exhale',
    'sleep.room',
    'sleep.threeam',
    'plan.missed',
    'sleep.bed',
    'sleep.worry',
    'plan.clear',
    'plan.grows',
    'sleep.wind',
    'sleep.caffeine',
    'sleep.noise',
    'sleep.screen',
    'body.evening',
    'sleep.alcohol',
    'sleep.anchor',
    'quiet.rested',
    'sleep.hours',
    'sleep.weekend',
    'sleep.light',
    'sleep.meal',
    'sleep.nap',
    'sleep.debt',
    'body.inertia',
    'quiet.kind',
    'sleep.clock',
    'quiet.bodyfirst',
    'focus.offline',
    'plan.carry',
  ],
  morning: [
    'breath.wake',
    'body.inertia',
    'attention.sensesmorning',
    'attention.anchor',
    'sleep.anchor',
    'attention.musclesmorningready',
    'attention.effort',
    'attention.grows',
    'body.dip',
    'body.firststeps',
    'sleep.light',
    'body.strength',
    'body.walk',
    'body.morningfood',
    'sleep.weekend',
    'body.morningprep',
    'body.sitting',
    'body.thirst',
    'sleep.hours',
    'sleep.nap',
    'body.appetite',
    'focus.three',
    'body.evening',
    'quiet.moving',
    'focus.ready',
    'sleep.wind',
    'sleep.debt',
    'plan.carry',
  ],
  focus: [
    'breath.exhale',
    'focus.nextstep',
    'attention.sensesfocus',
    'attention.anchor',
    'focus.phone',
    'attention.musclesfocusready',
    'attention.effort',
    'attention.grows',
    'body.dip',
    'focus.hard',
    'focus.ready',
    'focus.parkthought',
    'focus.readback',
    'focus.inbox',
    'anger.cues',
    'body.movement',
    'focus.blocks',
    'focus.badges',
    'body.walk',
    'sleep.anchor',
    'focus.words',
    'quiet.notice',
    'body.sitting',
    'sleep.caffeine',
    'anger.rumination',
    'body.inertia',
    'focus.place',
    'anger.control',
    'body.thirst',
    'focus.stop',
    'sleep.hours',
    'quiet.rested',
    'body.appetite',
    'quiet.moving',
    'sleep.light',
    'focus.done',
    'sleep.debt',
    'anger.boring',
    'quiet.gap',
    'quiet.kind',
    'quiet.thoughts',
    'plan.carry',
  ],
  quiet: [
    'breath.exhale',
    'quiet.two',
    'quiet.bodyfirst',
    'plan.missed',
    'attention.sensesquiet',
    'attention.musclesquietready',
    'attention.effort',
    'attention.grows',
    'quiet.gap',
    'quiet.beginner',
    'quiet.notice',
    'anger.cues',
    'quiet.onesound',
    'quiet.eyes',
    'quiet.namefeeling',
    'quiet.waiting',
    'body.dip',
    'quiet.thoughts',
    'quiet.boredom',
    'anger.control',
    'anger.rumination',
    'anger.meter',
    'anger.recovery',
    'body.movement',
    'sleep.anchor',
    'anger.belief',
    'body.thirst',
    'focus.phone',
    'anger.bucket',
    'quiet.rested',
    'anger.timeout',
    'focus.parkthought',
    'sleep.caffeine',
    'anger.boring',
    'body.sitting',
    'focus.badges',
    'body.inertia',
    'quiet.kind',
    'sleep.hours',
    'anger.expectation',
    'sleep.wind',
    'plan.carry',
  ],
};

export const PRE_ALL_GOAL_FIRST_PRESSURE_SEQUENCES: Record<PressureLessonTrack, readonly LessonId[]> = {
  stress: [
    'breath.exhale', 'stress.signs', 'attention.sensesstress', 'attention.anchor',
    'stress.load', 'attention.musclesstressready', 'attention.effort',
    'attention.grows', 'quiet.namefeeling', 'anger.oneproblem', 'focus.nextstep',
    'body.capacity', 'body.gentle', 'quiet.kind',
    'focus.three', 'focus.hard', 'focus.ready', 'focus.done', 'body.enough',
    'body.shareload', 'anger.askhelp',
    'stress.boundary', 'focus.inbox', 'focus.badges', 'focus.switch', 'focus.stop',
    'focus.blocks', 'quiet.smalldecision',
    'quiet.bodyfirst', 'quiet.onesound', 'quiet.waiting', 'quiet.eyes', 'quiet.two',
    'quiet.wander', 'quiet.moving',
    'body.restchoice', 'focus.offline', 'quiet.rested', 'sleep.worry', 'sleep.wind',
    'sleep.room', 'sleep.noise',
    'body.movement', 'body.sitting', 'body.thirst', 'body.dip', 'quiet.voice',
    'quiet.changemind', 'quiet.askadvice',
    'anger.afterstress', 'quiet.thoughts', 'quiet.trust', 'quiet.repair',
    'plan.missed', 'plan.clear', 'plan.carry',
  ],
  overthinking: [
    'breath.exhale', 'worry.loop', 'attention.sensesoverthinking', 'attention.anchor',
    'worry.facts', 'attention.musclesoverthinkingready', 'attention.effort',
    'attention.grows', 'quiet.thoughts', 'focus.parkthought', 'worry.uncertainty',
    'quiet.namefeeling', 'quiet.wander', 'quiet.kind',
    'anger.oneproblem', 'focus.nextstep', 'quiet.smalldecision', 'quiet.changemind',
    'quiet.askadvice', 'anger.askhelp', 'body.shareload',
    'focus.ready', 'focus.hard', 'focus.done', 'focus.three', 'focus.stop',
    'focus.switch', 'body.enough',
    'quiet.onesound', 'quiet.waiting', 'quiet.eyes', 'quiet.bodyfirst', 'quiet.two',
    'quiet.moving', 'quiet.boredom',
    'sleep.worry', 'sleep.wind', 'sleep.clock', 'sleep.threeam', 'sleep.room',
    'sleep.noise', 'sleep.screen',
    'focus.offline', 'quiet.rested', 'body.restchoice', 'body.capacity',
    'body.gentle', 'body.movement', 'body.sitting',
    'focus.phone', 'quiet.voice', 'quiet.trust', 'quiet.repair',
    'plan.missed', 'plan.clear', 'plan.carry',
  ],
  anger: [
    'breath.exhale', 'anger.meter', 'attention.sensesanger', 'attention.anchor',
    'anger.recovery', 'attention.musclesangerready', 'attention.effort',
    'attention.grows', 'anger.cues', 'anger.boring', 'quiet.namefeeling',
    'anger.bucket', 'anger.belief', 'quiet.gap',
    'anger.control', 'anger.oneproblem', 'anger.timeout', 'anger.expectation',
    'anger.askhelp', 'anger.assert', 'anger.send',
    'anger.rumination', 'quiet.thoughts', 'quiet.onesound', 'quiet.wander',
    'anger.repair', 'anger.afterstress', 'quiet.kind',
    'body.capacity', 'body.gentle', 'body.enough', 'body.shareload',
    'body.restchoice', 'focus.offline', 'quiet.rested',
    'sleep.debt', 'sleep.anchor', 'sleep.caffeine', 'sleep.wind', 'sleep.worry',
    'sleep.hours', 'sleep.room',
    'body.movement', 'body.sitting', 'body.thirst', 'body.dip', 'quiet.bodyfirst',
    'quiet.eyes', 'quiet.two',
    'anger.driving', 'quiet.smalldecision', 'quiet.voice', 'quiet.repair',
    'plan.missed', 'plan.clear', 'plan.carry',
  ],
};
