import type { LessonId } from './lessonCatalogue';
import type { PressureLessonTrack } from './pressureLessonTrack';

/** Three lesson paths share the same eight-week pressure Reset schedule. */
export const PRESSURE_LESSON_SEQUENCES: Record<PressureLessonTrack, readonly LessonId[]> = {
  stress: [
    'stress.signs', 'breath.exhale', 'attention.sensesstress', 'attention.anchor',
    'stress.load', 'attention.musclesstressready', 'attention.effort',
    'attention.grows', 'quiet.namefeeling', 'anger.oneproblem', 'focus.nextstep',
    'body.capacity', 'body.gentle', 'quiet.kind',
    'focus.three', 'focus.hard', 'focus.ready', 'focus.done', 'body.enough',
    'body.shareload', 'anger.askhelp',
    'stress.boundary', 'focus.inbox', 'focus.badges', 'focus.switch', 'focus.stop',
    'focus.blocks', 'quiet.smalldecision',
    'quiet.bodyfirst', 'quiet.onesound', 'quiet.waiting', 'quiet.eyes', 'quiet.two',
    'quiet.wander', 'quiet.moving',
    'body.restchoice', 'focus.offline', 'quiet.rested', 'sleep.worry', 'sleep.wind',
    'sleep.room', 'sleep.noise',
    'body.movement', 'body.sitting', 'body.thirst', 'body.dip', 'quiet.voice',
    'quiet.changemind', 'quiet.askadvice',
    'anger.afterstress', 'quiet.thoughts', 'quiet.trust', 'quiet.repair',
    'plan.missed', 'plan.clear', 'plan.carry',
  ],
  overthinking: [
    'worry.loop', 'breath.exhale', 'attention.sensesoverthinking', 'attention.anchor',
    'worry.facts', 'attention.musclesoverthinkingready', 'attention.effort',
    'attention.grows', 'quiet.thoughts', 'focus.parkthought', 'worry.uncertainty',
    'quiet.namefeeling', 'quiet.wander', 'quiet.kind',
    'anger.oneproblem', 'focus.nextstep', 'quiet.smalldecision', 'quiet.changemind',
    'quiet.askadvice', 'anger.askhelp', 'body.shareload',
    'focus.ready', 'focus.hard', 'focus.done', 'focus.three', 'focus.stop',
    'focus.switch', 'body.enough',
    'quiet.onesound', 'quiet.waiting', 'quiet.eyes', 'quiet.bodyfirst', 'quiet.two',
    'quiet.moving', 'quiet.boredom',
    'sleep.worry', 'sleep.wind', 'sleep.clock', 'sleep.threeam', 'sleep.room',
    'sleep.noise', 'sleep.screen',
    'focus.offline', 'quiet.rested', 'body.restchoice', 'body.capacity',
    'body.gentle', 'body.movement', 'body.sitting',
    'focus.phone', 'quiet.voice', 'quiet.trust', 'quiet.repair',
    'plan.missed', 'plan.clear', 'plan.carry',
  ],
  anger: [
    'anger.meter', 'breath.exhale', 'attention.sensesanger', 'attention.anchor',
    'anger.recovery', 'attention.musclesangerready', 'attention.effort',
    'attention.grows', 'anger.cues', 'anger.boring', 'quiet.namefeeling',
    'anger.bucket', 'anger.belief', 'quiet.gap',
    'anger.control', 'anger.oneproblem', 'anger.timeout', 'anger.expectation',
    'anger.askhelp', 'anger.assert', 'anger.send',
    'anger.rumination', 'quiet.thoughts', 'quiet.onesound', 'quiet.wander',
    'anger.repair', 'anger.afterstress', 'quiet.kind',
    'body.capacity', 'body.gentle', 'body.enough', 'body.shareload',
    'body.restchoice', 'focus.offline', 'quiet.rested',
    'sleep.debt', 'sleep.anchor', 'sleep.caffeine', 'sleep.wind', 'sleep.worry',
    'sleep.hours', 'sleep.room',
    'body.movement', 'body.sitting', 'body.thirst', 'body.dip', 'quiet.bodyfirst',
    'quiet.eyes', 'quiet.two',
    'anger.driving', 'quiet.smalldecision', 'quiet.voice', 'quiet.repair',
    'plan.missed', 'plan.clear', 'plan.carry',
  ],
};
