import type { Lesson, LessonId } from '../../lessons/domain/lessonCatalogue';

/** Short chapter titles for the journey; the full teaching titles stay in the lessons. */
const LESSON_TITLES: Record<LessonId, string> = {
  'breath.exhale': 'The Long Exhale',
  'breath.wake': 'A Brighter Start',

  'plan.grows': 'Small Wins',
  'plan.hour': 'Beyond Willpower',
  'plan.stacking': 'The Habit Link',
  'plan.low': 'Easy Is Enough',
  'plan.expect': 'Find Your Rhythm',
  'plan.two': 'Room for a Pause',
  'plan.consistency': 'Coming Back',
  'plan.bad': 'Hard Days Count',
  'plan.missed': 'A Fresh Start',
  'plan.streak': 'Progress, Not Points',
  'plan.week': 'Bigger Picture',
  'plan.after': 'Make It Yours',

  'sleep.anchor': 'Sleep Rhythm',
  'sleep.light': 'Let the Light In',
  'sleep.caffeine': 'Late Coffee',
  'sleep.wind': 'The Quiet Hour',
  'sleep.bed': 'A Place for Sleep',
  'sleep.threeam': 'Awake at 3',
  'sleep.worry': 'Tomorrow Can Wait',
  'sleep.alcohol': 'Nightcap Myth',
  'sleep.hours': 'Enough Sleep',
  'sleep.weekend': 'Weekend Shift',
  'sleep.nap': 'The Short Nap',
  'sleep.debt': 'Running on Empty',
  'sleep.room': 'Room to Rest',
  'sleep.noise': 'Less Noise',
  'sleep.screen': 'Before the Last Scroll',
  'sleep.meal': 'Dinner Timing',
  'sleep.clock': 'Watching the Clock',

  'body.inertia': 'Beyond the Fog',
  'body.movement': 'A Little Movement',
  'body.dip': 'Afternoon Dip',
  'body.walk': 'After the Last Bite',
  'body.sitting': 'Time to Stand',
  'body.strength': 'Building Strength',
  'body.appetite': 'Sleep and Hunger',
  'body.evening': 'When Lights Dim',
  'body.thirst': 'Tired or Thirsty?',
  'body.morningprep': 'Tomorrow Starts Now',
  'body.firststeps': 'Your First Steps',
  'body.morningfood': 'An Easier Breakfast',

  'anger.recovery': 'Before You Reply',
  'anger.meter': 'How Angry Am I?',
  'anger.cues': 'Anger Signals',
  'anger.boring': 'Hungry or Angry?',
  'anger.belief': 'The Story You Tell',
  'anger.expectation': 'Say What You Need',
  'anger.bucket': 'Stress Adds Up',
  'anger.control': 'Your Control',
  'anger.timeout': 'Taking a Timeout',
  'anger.assert': 'Clear, Not Cruel',
  'anger.send': 'Reread First',
  'anger.rumination': 'Replay Loop',
  'anger.driving': 'Behind the Wheel',
  'anger.repair': 'Making It Right',
  'anger.oneproblem': 'One Thing at a Time',
  'anger.askhelp': 'You Can Ask',
  'anger.afterstress': 'After the Storm',

  'focus.ready': 'Ready Is a Myth',
  'focus.switch': 'A Note for Later',
  'focus.phone': 'Out of Reach',
  'focus.blocks': 'A Little Focus',
  'focus.three': 'Your Top Three',
  'focus.hard': 'An Easier Way In',
  'focus.inbox': 'The Inbox Trap',
  'focus.badges': 'The Red Dot Pull',
  'focus.words': 'Words or Music?',
  'focus.place': 'Focus Spot',
  'focus.stop': 'Leave a Way Back',
  'focus.done': 'The Finish Line',
  'focus.nextstep': 'The Next Step',
  'focus.parkthought': 'Park the Thought',
  'focus.readback': 'Your Own Words',
  'focus.homelaundry': 'One Load at a Time',
  'focus.homedishes': 'Space at the Sink',
  'focus.homeshared': 'Who Does What?',
  'focus.phonepurpose': 'Why This App?',
  'focus.phonemessages': 'Messages Can Wait',
  'focus.phonebed': 'Phone Parking',

  'quiet.gap': 'The Space to Pause',
  'quiet.notice': 'Name the Feeling',
  'quiet.wander': 'Mind Wanders',
  'quiet.beginner': 'New at This?',
  'quiet.two': 'Two Is Enough',
  'quiet.eyes': 'Eyes Open Is Okay',
  'quiet.bodyfirst': 'Your Body Speaks',
  'quiet.thoughts': 'More Than a Thought',
  'quiet.boredom': 'Room for Boredom',
  'quiet.moving': 'Stillness in Motion',
  'quiet.rested': 'Rest or Scroll?',
  'quiet.kind': 'A Kinder Voice',
  'quiet.onesound': 'One Sound',
  'quiet.waiting': 'While You Wait',
  'quiet.namefeeling': 'What Am I Feeling?',
  'quiet.smalldecision': 'What Fits Today?',
  'quiet.changemind': 'Changing Your Mind',
  'quiet.askadvice': 'A Useful Question',

  'focus.home': 'More Than the Mess',
  'focus.visible': 'Start in Sight',
  'focus.return': 'Come Back',
  'focus.loop': 'Before the Scroll',
  'focus.pull': 'The Pull to Scroll',
  'focus.offline': 'A Break That Rests',
  'body.capacity': 'Energy Today',
  'body.gentle': 'Small Steps',
  'body.enough': 'What Is Enough?',
  'quiet.trust': 'You Came Back',
  'quiet.voice': 'On Your Own Side',
  'quiet.repair': 'After a Miss',

  'focus.category': 'One Small Job',
  'focus.eyes': 'Start with One Thing',
  'focus.sort': 'Everything in Its Place',
  'focus.bin': 'A Bin Nearby',
  'focus.timer': 'A Time to Stop',
  'focus.landing': 'One Clear Surface',
  'focus.doorway': 'When You Get Home',
  'focus.edge': 'Your Finish Line',
  'focus.livedin': 'Mess Is Not You',
  'focus.ending': 'The Last Scroll',
  'focus.unlock': 'Why Am I Here?',
  'focus.default': 'Break the Shortcut',
  'focus.hands': 'After the Phone',
  'focus.charger': 'Charge and Rest',
  'focus.save': 'What Matters',
  'focus.wait': 'The Alert Can Wait',
  'focus.company': 'One Screen',
  'focus.capture': 'Save It and Leave',

  'body.corner': 'One Part of Today',
  'body.signal': 'Body Needs',
  'body.comfort': 'How It Felt',
  'body.floor': 'An Easier Start',
  'body.sight': 'Care in Plain Sight',
  'body.decision': 'Needs First',
  'body.hour': 'A Fresh Afternoon',
  'body.finish': 'A Place to Stop',
  'body.returnpath': 'An Easy Way Back',
  'quiet.when': 'Name the Moment',
  'quiet.cue': 'A Clear Reminder',
  'quiet.no': 'A Smaller Promise',
  'quiet.yes': 'Your Promise',
  'quiet.story': 'One Miss',
  'quiet.yesterday': 'What Worked',
  'quiet.plain': 'Keep It Small',
  'quiet.boundary': 'Time That Matters',
  'quiet.receipt': 'What You Did Counts',
  'body.restchoice': 'The Rest You Need',
  'body.shareload': 'Share the Load',
  'body.energycost': 'The Whole Trip',

  'attention.senses': 'Here and Now',
  'attention.muscles': 'Hold, Then Let Go',
  'attention.return': 'What You Noticed',
  'attention.week': 'Your First Week',
  'attention.grows': 'Another Pause',
  'attention.sensesmorning': 'Here and Now',
  'attention.musclesmorning': 'Hold, Then Let Go',
  'attention.sensesfocus': 'Here and Now',
  'attention.musclesfocus': 'Hold, Then Let Go',
  'attention.senseshome': 'Here and Now',
  'attention.muscleshome': 'Hold, Then Let Go',
  'attention.sensesphone': 'Here and Now',
  'attention.musclesphone': 'Hold, Then Let Go',
  'attention.sensesrecovery': 'Here and Now',
  'attention.musclesrecovery': 'Hold, Then Let Go',
  'attention.sensesselftrust': 'Here and Now',
  'attention.musclesselftrust': 'Hold, Then Let Go',
  'attention.sensesquiet': 'Here and Now',
  'attention.musclesquiet': 'Hold, Then Let Go',
  'attention.musclesmorningready': 'Hold, Then Let Go',
  'attention.musclesfocusready': 'Hold, Then Let Go',
  'attention.muscleshomeready': 'Hold, Then Let Go',
  'attention.musclesphoneready': 'Hold, Then Let Go',
  'attention.musclesrecoveryready': 'Hold, Then Let Go',
  'attention.musclesselftrustready': 'Hold, Then Let Go',
  'attention.musclesquietready': 'Hold, Then Let Go',
  'attention.sensesstress': 'When It Is Too Much',
  'attention.musclesstress': 'Stress in Your Body',
  'attention.sensesoverthinking': 'Out of Your Head',
  'attention.musclesoverthinking': 'Ease the Tension',
  'attention.sensesanger': 'A Pause to Reply',
  'attention.musclesanger': 'Anger in Your Body',
  'attention.musclesstressready': 'Stress in Your Body',
  'attention.musclesoverthinkingready': 'Ease the Tension',
  'attention.musclesangerready': 'Anger in Your Body',
  'attention.anchor': 'A Place to Return',
  'attention.effort': 'Gentle Is Enough',

  'plan.clear': 'The First Hurdle',
  'plan.carry': 'Room to Begin',
  'quiet.prepare': 'An Easier Promise',
  'stress.signs': 'Stress Signals',
  'stress.load': 'Too Much for Today?',
  'stress.boundary': 'Know Your Limits',
  'worry.loop': 'The Worry Loop',
  'worry.facts': 'Facts or Fears?',
  'worry.uncertainty': 'The Unknown',
};

export function planLessonTitle(lesson: Pick<Lesson, 'id'> | null): string {
  return lesson == null ? 'A Small Step' : LESSON_TITLES[lesson.id];
}
