import { StyleSheet } from 'react-native';
import { card } from '../../../theme/card';
import { colors } from '../../../theme/colors';
import { spacing } from '../../../theme/spacing';
import { fonts, typography } from '../../../theme/typography';

export const paywallStepStyles = StyleSheet.create({
  stepContainer: {
    gap: spacing.xl,
  },
  heroContainer: {
    paddingTop: spacing['3xl'],
    paddingHorizontal: spacing.sm,
    alignItems: 'center',
    gap: spacing.sm,
  },
  bellWrap: {
    marginTop: spacing.sm,
  },
  bellHint: {
    ...typography.body.small,
    color: colors.text.tertiary,
    textAlign: 'center',
  },
  bellBadge: {
    position: 'absolute',
    top: 46,
    right: 48,
    minWidth: 52,
    height: 52,
    borderRadius: 26,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.error[500],
  },
  bellBadgeText: {
    ...typography.heading.heading1,
    fontFamily: fonts.semibold,
    fontWeight: '500',
    color: colors.neutral[0],
  },
  headerCopy: {
    alignItems: 'flex-start',
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
  },
  eyebrow: {
    ...typography.body.medium,
    fontFamily: fonts.semibold,
    fontWeight: '500',
    color: 'rgba(255,255,255,0.75)',
    textAlign: 'left',
  },
  title: {
    ...typography.display.display3,
    fontFamily: fonts.semibold,
    fontWeight: '500',
    color: colors.neutral[0],
    textAlign: 'left',
  },
  titleDivider: {
    alignSelf: 'stretch',
    height: StyleSheet.hairlineWidth,
    backgroundColor: 'rgba(255,255,255,0.35)',
    marginTop: spacing.xs,
    marginBottom: spacing.xs,
  },
  stepHeader: {
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
  },
  stepTitle: {
    ...typography.display.display3,
    fontFamily: fonts.semibold,
    fontWeight: '500',
    color: colors.text.primary,
    textAlign: 'center',
  },
  stepSubtitle: {
    ...typography.body.medium,
    color: colors.text.secondary,
    textAlign: 'center',
  },
  stepFinePrint: {
    ...typography.body.small,
    color: colors.text.tertiary,
    textAlign: 'center',
    marginTop: spacing.xs,
  },
  valueHeader: {
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
  },
  valueTitle: {
    ...typography.display.display1,
    fontFamily: fonts.semibold,
    fontWeight: '500',
    color: colors.text.primary,
    textAlign: 'center',
    letterSpacing: -0.6,
  },
  valueTitleUnderline: {
    width: 56,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.primary.blue600,
    marginTop: spacing.xs,
    marginBottom: spacing.xs,
  },
  planHeadline: {
    ...typography.display.display3,
    fontFamily: fonts.semibold,
    fontWeight: '500',
    color: colors.text.primary,
    textAlign: 'center',
    letterSpacing: -0.3,
  },
  sectionTitle: {
    ...typography.heading.heading1,
    fontFamily: fonts.semibold,
    fontWeight: '500',
    color: colors.text.primary,
    textAlign: 'center',
  },
  radarBlock: {
    alignItems: 'center',
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  radarLegend: {
    flexDirection: 'row',
    gap: spacing.lg,
    alignSelf: 'center',
    marginTop: spacing.lg,
  },
  radarLegendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  radarLegendDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  radarLegendDotTarget: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: colors.orange[500],
  },
  radarLegendLabel: {
    ...typography.caption.caption1,
    fontFamily: fonts.semibold,
    fontWeight: '500',
    color: colors.text.secondary,
  },
  radarWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -spacing.xl,
  },
  radarFooter: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: spacing.xs,
    alignSelf: 'center',
    marginTop: spacing.xs,
  },
  radarFooterLabel: {
    ...typography.caption.caption1,
    color: colors.text.tertiary,
  },
  radarFooterValue: {
    ...typography.heading.heading2,
    fontFamily: fonts.semibold,
    fontWeight: '500',
    color: colors.primary.blue600,
  },
  baselineStrip: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  baselineChip: {
    ...card.base,
    ...card.shadow,
    flex: 1,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.sm,
    backgroundColor: colors.background.elevated,
    alignItems: 'center',
    gap: 2,
  },
  baselineChipValue: {
    ...typography.heading.heading1,
    fontFamily: fonts.semibold,
    fontWeight: '500',
    color: colors.primary.blue600,
    letterSpacing: -0.4,
  },
  baselineChipLabel: {
    ...typography.caption.caption2,
    color: colors.text.tertiary,
    textAlign: 'center',
    textTransform: 'lowercase',
  },
  ladder: {
    ...card.base,
    ...card.shadow,
    backgroundColor: colors.background.elevated,
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.md,
  },
  ladderRow: {
    flexDirection: 'row',
    gap: spacing.md,
  },
  ladderRail: {
    alignItems: 'center',
    width: 24,
  },
  ladderNode: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: colors.primary.blue600,
    backgroundColor: colors.background.elevated,
    marginTop: spacing.xs,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ladderNodeFinal: {
    backgroundColor: colors.primary.blue600,
  },
  ladderNodeInner: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.background.elevated,
  },
  ladderLine: {
    width: 2,
    flex: 1,
    minHeight: 36,
    backgroundColor: colors.primary.blue100,
    marginTop: 2,
  },
  ladderCopy: {
    flex: 1,
    paddingBottom: spacing.md,
  },
  ladderDay: {
    ...typography.caption.caption1,
    fontFamily: fonts.semibold,
    fontWeight: '500',
    color: colors.text.brand,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  ladderTitle: {
    ...typography.body.medium,
    fontFamily: fonts.semibold,
    fontWeight: '500',
    color: colors.text.primary,
    marginTop: 2,
  },
  ladderBody: {
    ...typography.body.small,
    color: colors.text.secondary,
    marginTop: 2,
  },
  valueSubtitle: {
    ...typography.body.medium,
    color: colors.text.secondary,
    textAlign: 'center',
    paddingHorizontal: spacing.md,
  },
  trialNote: {
    ...typography.caption.caption1,
    fontFamily: fonts.semibold,
    fontWeight: '500',
    color: colors.primary.blue600,
    textAlign: 'center',
    marginTop: spacing.xs,
  },
  trialNoteDark: {
    color: colors.primary.blue200,
    textAlign: 'left',
  },
  valueGrid: {
    gap: spacing.sm,
  },
  valueTile: {
    ...card.base,
    ...card.shadow,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.md,
    backgroundColor: colors.background.elevated,
  },
  valueTileIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.neutral[900],
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 3,
  },
  valueTileCopy: {
    flex: 1,
  },
  valueTileTitle: {
    ...typography.heading.heading2,
    fontFamily: fonts.semibold,
    fontWeight: '500',
    color: colors.text.primary,
  },
  valueTileBody: {
    ...typography.body.small,
    color: colors.text.secondary,
    marginTop: 2,
  },
  timeline: {
    alignSelf: 'stretch',
    paddingHorizontal: spacing.md,
  },
  timelineRow: {
    flexDirection: 'row',
    gap: spacing.md,
  },
  timelineRail: {
    alignItems: 'center',
    width: 42,
  },
  timelineIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary.blue600,
  },
  timelineLine: {
    width: 6,
    flex: 1,
    minHeight: 80,
    backgroundColor: colors.primary.blue100,
  },
  timelineCopy: {
    flex: 1,
    paddingBottom: spacing['2xl'],
  },
  timelineLabel: {
    ...typography.heading.heading1,
    fontFamily: fonts.semibold,
    fontWeight: '500',
    color: colors.text.primary,
  },
  timelineBody: {
    ...typography.body.small,
    color: colors.text.secondary,
    marginTop: spacing.xs,
  },
  cardsLoading: {
    minHeight: 180,
    alignItems: 'center',
    justifyContent: 'center',
  },
  planCards: {
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
});
