import type { IconName } from '../../components/common/icons/paths';
import {
  programDayDefinition,
  type ProgramPresetRevision,
} from '../program/domain/programCatalogue';

// One decorative motif per day of the longest plan, kept stable as practices repeat.
const DAY_COIN_ICONS: readonly IconName[] = [
  'coin-leaf',
  'coin-balloon',
  'coin-box',
  'heart',
  'lotus',
  'coin-wave',
  'coin-sun',
  'coin-cloud',
  'meditation',
  'coin-eye',
  'journal',
  'coin-wind',
  'coin-drop',
  'coin-book',
  'coin-moon',
  'streak',
  'coin-pencil',
  'breath-hold',
  'coin-triangle',
  'sense-ear',
  'coin-snowflake',
  'coin-bolt',
  'calendar',
  'flask',
  'body-hand',
  'sunrise',
  'profile',
  'coin-star',
  'clock',
  'microscope',
  'coffee-outline',
  'walk',
  'shield-check',
  'research-paper',
  'face-calm',
  'bell',
  'dumbbell',
  'mood-focus',
  'sense-nose',
  'todo-grounding',
  'stethoscope',
  'briefcase',
  'twinkle',
  'mood-overthinking',
  'todo-shower',
  'sense-mouth',
  'todo-curtains',
  'mood-restless',
  'plane',
  'mood-overwhelmed',
  'todo-screen-free',
  'mood-wind-down',
  'todo-meal',
  'mood-low-mood',
  'celebration',
  'trophy',
];

/** The day's visual marker; the lesson and Reset remain defined by the preset. */
export function dayCoinIcon(preset: ProgramPresetRevision | null, day: number): IconName {
  if (preset == null || programDayDefinition(preset, day) == null) return 'coin-star';
  return DAY_COIN_ICONS[day - 1] ?? 'coin-star';
}
